### PR TITLE
Kernel upstream

### PR DESCRIPTION
**Pull request by Sleppyiecat**
from version 4.14.212 to 4.14.213

### CODE REVIEW

**Comment by Sleppyiecat** [comment]
sorry sir i forgot to fix conflicts for those 2 before XDD

**Comment by danielml3** [comment]
I merged manually the 4.14.213 tag, and as I said, I won't accept the other commits in PRs not related to new tag merges.

**Comment by Sleppyiecat** [comment]
sorry those 2 last was just impostors, i missunderstood what was wrong with them

**Comment by Sleppyiecat** [comment]
lmao

**Comment by danielml3** [comment]
Also, it seems the merge makes the phone to freeze after a few mins, need to debug that xD

**Comment by Sleppyiecat** [comment]
caused by 2 last commits i reverted i think

**Pull request closed without merging**
